import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Check, ChevronRight, Circle, Clock3, ListChecks, X } from "lucide-react";
import type { SearchableStock } from "./StockAnalysis";
import "./watchlist.css";

type Segment = "진행 중" | "일반 관심" | "오늘 종료";
type Filter = "전체" | "진입 대기" | "보유" | "청산";
export type EntryRecord = { price:number; quantity:number; time:string; step:number };
export type Observation = { stock:SearchableStock; startedAt:string; entries:EntryRecord[]; confidence:number };
export type EndedObservation = { stock:SearchableStock; endedAt:string; reason:string; entryCount:number };

const timeNow = () => new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",hour12:false});

export default function Watchlist({favorites,observations,ended,onStart,onEntry,onEnd}:{favorites:SearchableStock[];observations:Observation[];ended:EndedObservation[];onStart:(stock:SearchableStock)=>void;onEntry:(code:string,entry:EntryRecord)=>void;onEnd:(code:string,reason:string)=>void}) {
  const [segment,setSegment] = useState<Segment>("진행 중"), [filter,setFilter] = useState<Filter>("전체"),
    [featuredCode,setFeaturedCode] = useState(""), [sheet,setSheet] = useState<"entry"|"end"|null>(null), topRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(observations.length)setFeaturedCode(observations.at(-1)!.stock.code)},[observations.length]);
  const active = useMemo(()=>observations.map(item=>({...item,stage:item.entries.length?"보유" as const:"진입 대기" as const})),[observations]),
    filtered = filter==="전체"?active:active.filter(item=>item.stage===filter), featured=filtered.find(item=>item.stock.code===featuredCode)??filtered[0],
    average = featured?.entries.length?Math.round(featured.entries.reduce((sum,item)=>sum+item.price*item.quantity,0)/featured.entries.reduce((sum,item)=>sum+item.quantity,0)):0,
    counts=(name:Filter)=>name==="전체"?active.length:active.filter(item=>item.stage===name).length,
    expand=(code:string)=>{setFeaturedCode(code);topRef.current?.scrollIntoView({behavior:"smooth"})},
    saveEntry=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);onEntry(featured.stock.code,{price:Number(data.get("price")),quantity:Number(data.get("quantity")),time:String(data.get("time")),step:featured.entries.length+1});setSheet(null)},
    saveEnd=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);onEnd(featured.stock.code,String(data.get("reason")));setSheet(null)};
  return <div className="watchlist" ref={topRef}>
    <header className="watch-header"><h1>관심 종목</h1><p><b>● 실시간 정상</b> · {timeNow()}</p></header>
    <div className="watch-segments" role="tablist">{(["진행 중","일반 관심","오늘 종료"] as Segment[]).map(item=><button role="tab" aria-selected={segment===item} className={segment===item?"active":""} onClick={()=>setSegment(item)} key={item}>{item}</button>)}</div>
    {segment==="진행 중"&&<><div className="watch-filters">{(["전체","진입 대기","보유","청산"] as Filter[]).map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item} {counts(item)}</button>)}</div>
      {!featured?<section className="watch-empty"><p>현재 관찰 중인 종목이 없습니다.</p><small>종목 탭에서 관찰 후보를 확인하고 관찰을 시작해보세요.</small></section>:<><section className="watch-featured"><div className="watch-stock-head"><div><h2>{featured.stock.name}</h2><small>{featured.stock.code} · {featured.stock.market}</small></div><div><strong className={featured.stock.changeRate>=0?"positive":"negative"}>{featured.stock.changeRate>=0?"+":""}{featured.stock.changeRate.toFixed(1)}%</strong><span>{featured.stage}</span><small>현재가 {featured.stock.price.toLocaleString("ko-KR")}원</small></div></div><div className="watch-detail-grid"><div className="watch-timeline"><div><i className="done"><Check/></i><b>관찰 시작</b><time>{featured.startedAt}</time></div>{featured.entries.length?<><div><i className="current"><Circle/></i><b>{featured.entries.at(-1)!.step}차 진입</b><time>{featured.entries.at(-1)!.time}</time></div><div><i><Circle/></i><b>보유 관찰</b><time>진행 중</time></div></>:<><div><i className="current"><Circle/></i><b>확인 조건</b><time>2 / 3</time></div><div><i><Circle/></i><b>진입 확인 대기</b><time>현재</time></div></>}</div><dl><div><dt>{featured.entries.length?"평균 단가":"현재 상태"}</dt><dd>{featured.entries.length?`${average.toLocaleString("ko-KR")}원`:"관찰 중"}</dd></div><div><dt>Confidence</dt><dd>{featured.confidence} / 100</dd></div><div><dt>Flow Shift</dt><dd><em>매수 확인 중</em></dd></div><div><dt>보유 수량</dt><dd>{featured.entries.reduce((sum,item)=>sum+item.quantity,0).toLocaleString("ko-KR")}주</dd></div></dl></div><div className="watch-actions"><button onClick={()=>setSheet(featured.entries.length?"end":"entry")}>{featured.entries.length?"청산 기록":"진입 기록"}</button><button onClick={()=>setSheet("end")}>관찰 종료</button></div></section><section className="watch-list">{filtered.filter(item=>item.stock.code!==featured.stock.code).map(item=><button className={item.entries.length?"brand":"info"} onClick={()=>expand(item.stock.code)} key={item.stock.code}><i/><span><b>{item.stock.name}</b><small>{item.stock.code} · {item.stock.market}</small></span><span><b>{item.entries.length?`${item.entries.length}차 진입 · 보유`:"진입 확인 대기"}</b><small>{item.entries.length?`${item.entries.reduce((sum,entry)=>sum+entry.quantity,0)}주 보유`:"조건 2/3"}</small></span><span>Confidence {item.confidence}</span><ChevronRight/></button>)}</section></>}
      <button className="close-summary" onClick={()=>setFilter("청산")}><span><Clock3/> 장 마감까지 57분</span><span><ListChecks/> 보유 기록 {active.filter(item=>item.entries.length).length}</span></button></>}
    {segment==="일반 관심"&&<section className="watch-list favorite-list">{favorites.length?favorites.map(stock=><div className="favorite-row" key={stock.code}><span><b>{stock.name}</b><small>{stock.code} · {stock.market}</small></span><span><b>{stock.price.toLocaleString("ko-KR")}원</b><small>{stock.changeRate>=0?"+":""}{stock.changeRate.toFixed(2)}%</small></span><button onClick={()=>{onStart(stock);setSegment("진행 중")}}>관찰 시작</button></div>):<div className="watch-empty"><p>아직 일반 관심 종목이 없습니다.</p><small>종목 분석에서 일반 관심 등록을 눌러보세요.</small></div>}</section>}
    {segment==="오늘 종료"&&<section className="watch-list ended-list">{ended.length?ended.map((item,index)=><div className="favorite-row" key={`${item.stock.code}-${item.endedAt}-${index}`}><span><b>{item.stock.name}</b><small>{item.stock.code} · {item.stock.market}</small></span><span><b>{item.reason}</b><small>{item.entryCount?`진입 ${item.entryCount}회`:"미진입 종료"}</small></span><time>{item.endedAt}</time></div>):<div className="watch-empty"><p>오늘 종료된 관찰 기록이 없습니다.</p></div>}</section>}
    {sheet&&featured&&<div className="record-backdrop"><form className="record-sheet" onSubmit={sheet==="entry"?saveEntry:saveEnd}><button type="button" className="record-close" onClick={()=>setSheet(null)} aria-label="기록 닫기"><X/></button><h2>{sheet==="entry"?`${featured.entries.length+1}차 진입 기록`:featured.entries.length?"청산·종료 기록":"관찰 종료"}</h2><p>{featured.stock.name} · {featured.stock.code}</p>{sheet==="entry"?<><label>진입 가격<input name="price" type="number" min="1" required defaultValue={featured.stock.price}/></label><label>수량<input name="quantity" type="number" min="1" required defaultValue="1"/></label><label>진입 시각<input name="time" type="time" required defaultValue={new Date().toTimeString().slice(0,5)}/></label><small>저장하면 평균 단가와 보유 수량을 다시 계산합니다.</small></>:<><label>종료 이유<select name="reason" defaultValue={featured.entries.length?"사용자 청산":"진입하지 않음"}><option>신호 약화</option><option>무효 조건 충족</option><option>진입하지 않음</option><option>사용자 청산</option><option>사용자 직접 종료</option></select></label><small>{featured.entries.length?"종료하면 진행 중에서 제거되고 오늘 종료에 청산 기록으로 남습니다.":"종료하면 진행 중에서 제거되고 오늘 종료에 미진입 종료로 남습니다."}</small></>}<footer><button type="button" onClick={()=>setSheet(null)}>취소</button><button type="submit">기록 저장</button></footer></form></div>}
  </div>;
}
